language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsecret-1-dev
deploy:
  provider: npm
  email: twilio-ci@twilio.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  edge: true
  on:
    tags: true
    node: lts/*

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms: $SLACK_TOKEN
