language: node_js
node_js:
  # Disabling for Node 16 until audit issue is resolved: https://travis-ci.com/github/twilio/twilio-cli-core/jobs/512495850
  # - node
  - lts/*
  - '10'
before_install:
- sudo apt-get update
- sudo apt-get install -y libsecret-1-dev
script:
- npm run test
- sonar-scanner
deploy:
  provider: npm
  email: team_interfaces@twilio.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  edge: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+$"
    node: lts/*
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: co5l1LIDXNac0VVXrOaOvpqjqkVraMDCW5uErSQ9W3KUSjyRf88sukrRL83xIFMu0U4+W6bj8aHU7DCaE9M1yyndv/GFjr7oAYMdc2VbcHCCMGGBZp3SAo/OgIqoS+GZJMaN2D0Hy9PtkMuzXiZ374WIraj6XJQjCb289WUZZUJJ9f7xEh9ewrIsNXAorfLlNxoxXZbMAmq51j85yen+y0uOKJyV9IlRdp+XGSGPZEFYTDkJgqf0Adah+RfCfaSOzpDWneqLdiXNun6d9yn+0Ok9d9odsg9lFMYyfC2s58R5evxQJrW6lXmV+wwXNZJRxVX3dhwRm1LmKlXs/fmmhL03tWWNCx9+brzq/KniuXhduQOlO181C3HY76LOLJvhig/UYzOTNccxVVVkFTnL4nTqxOO9tQl9FOj0x8X+8BPit9cVgkzXlmD0delDANE7rX0b8kkSzhL+MH5MX85k+3KBlVnTsfDRu+9iPaCt/+GSzFN2u4pIggRVFeea0hnljCIL3U1ZxNJdWDjfQzWuqE5jUELshmftr32Ty5cbn7pfrFfYQ+4kVeAMjweoT5+OcqAYihaD811ItzPO6eApaTZM6x6ZEbtLuvYAI+2AbOnEBqgfMcbzgZFIvhrnzF5ZdmKWe+8+2oENROuS1xkRHSrMr5ipahdSage19zNnO0s=
addons:
  sonarcloud:
    organization: twilio
    token:
      secure: XXvLAzUmE28YrSIS9WCpS5OxX3NbryHwUswjdPpncKIO/6xbQpWteFUVplBL2hj4yWFsfvoz0jGBTPgUe8jy0DPLHkbP3PIkXYB2UvNSC1N5YEDOmRSXzJQYpIP+eXvlE1lUy9GdZSuolfdXElLALq25Eg3WF2KZAOBZyu63k0lI37zLOdX2yW3Vf96GCB5jUYpu1zSd8ojW0MWbLVmcyn39lkXD1M0IYJDEiPk0XORF7O3kgDPyCHY8UyMuqibZO1z5XHYDH1Xl5377woBqi+bn1er5e8/h5MKYBSXrhUuRiZHaxbOLP2bF0Tsz/q/CKiWktzumknHSVJugSEj+mtRjCGuU6M06z7zd83mCseupVmsUT4y6hVzWe9vejvL4sUUcgwDtxqUp/OXlQNgTxn2N/bUNc8udc5L6sNAh/y9OaHib3SIhxCO8a0Rg7wolTa9HFWet4dnUISUG0n1vBlIKF5zdK+VJNCmZf1TbbCCfGcg5oSB6GlBuXu31r7xw6UA+LBsqCZxhnGyLhFwygtVw051m1gBun9sH4FcHOhuudajTk7hnpz0bYuGrpamVJrsOoMW1+TD7BJk1379mjUMMt2rV5eBXhV7jG99Wz1LxWmYgoXIMf5u1JO3dwzoXi2ECxCzr+XkfXtKszIe2mkVM7Ou3vj5ia4ySaQTyF3g=
